alias vi=nvim
alias ss='source ~/.bashrc'
alias bb='vi ~/.bashrc'
alias ba='vi ~/.bash_aliases'
alias bs='vi ~/.git_secret'
alias r='cd ~/repos && pwd'
alias vl='vi ~/.config/nvim/init.lua'
alias vv='vi ~/.config/nvim/vimrc.vim'
alias gb='git branch'
alias gl='git log'
alias pg='git pull origin $(git branch --show-current)'
alias gp='git push origin $(git branch --show-current)'
alias gs='git status'
alias gd='git diff'
alias ga='git add --all'
alias i='ipython'
alias python=python3
alias v="vagrant ssh"
alias tt='vi ~/.tmux.conf'
alias t='tree -a -I "*.pyc|*__pycache__|.git|.data|.pytest_cache|.ruff_cache"'
alias p3=python3
alias l='ls -lrta'
