# remap prefix
unbind C-b
set-option -g prefix `
bind-key ` send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'


set -g mouse on
set -g pane-border-style fg=black

set-option -sg escape-time 10
set-option -g focus-events on
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ',xterm-256color:Tc'
set-option -g history-limit 30000
set-window-option -g aggressive-resize
setw -g mode-keys vi
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi v send -X begin-selection
bind P paste-buffer
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# bind ctrl-C to escape
bind-key -n C-c send-keys Escape


run '~/.tmux/plugins/tpm/tpm'
# run-shell ~/clone/path/continuum.tmux

