set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g pane-border-style fg=black

set -g @sessionx-bind 's'
bind l select-pane -t :.+
bind h select-pane -t :.-

unbind-key -T copy-mode-vi v

setw -g mode-keys vi
bind -T copy-mode-vi 'r' send -X rectangle-toggle  # Begin selection in copy mode.
bind -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.
bind P paste-buffer
bind -T root C-c if-shell -F '#{==:#{pane_mode},tree-mode}' 'send-keys Escape' 'send-keys C-c'
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -sg escape-time 10
set -g focus-events on
set -g default-terminal "screen-256color"
set -ga terminal-overrides ',xterm-256color:Tc'
set -g history-limit 30000
set-window-option -g aggressive-resize
# set -ag pane-active-border fg=magenta

set -g status on
set -g status-left ""
# Show current task in status bar
set -g status-left "#(~/.tmux/get_current_task.py)                                             #(~/.tmux/get_git_branch.sh #{pane_current_path})"
set -g status-left-length 150
set -g status-right "#{session_name}"
set -g status-style bg=colour17,fg=colour248

set -g window-status-format ""
set -g window-status-current-format ""
set -g status-interval 1
set -g status-position bottom
set -g status-right-length 50
set -g display-time 200
set -g message-style bg=default,fg=default
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-sessionx'
run '~/.tmux/plugins/tpm/tpm'

